# Generated by Django 5.2.4 on 2025-09-08 09:02

import django.core.validators
import django.db.models.deletion
import trucks.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expense category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the expense category', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TruckLogisticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('truck_number', models.CharField(max_length=20)),
                ('transporter', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('destination', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('on_transit', 'On Transit'), ('offloaded', 'Offloaded'), ('did_not_load', "Didn't Load"), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on_transit', max_length=20)),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('partial', 'Partial'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='pending', max_length=20)),
                ('rate_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_transport_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('litres_of_fuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_per_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('source_document', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legacy Truck Logistics Record',
                'verbose_name_plural': 'Legacy Truck Logistics Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cargo type name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the cargo type', null=True)),
                ('unit_of_measure', models.CharField(default='tons', help_text='Unit of measurement (tons, cubic meters, pieces, etc.)', max_length=20)),
                ('is_hazardous', models.BooleanField(default=False, help_text='Whether this cargo type is hazardous')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cargo type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo Type',
                'verbose_name_plural': 'Cargo Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='trucks_carg_name_f43b55_idx')],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination name', max_length=100, unique=True)),
                ('region', models.CharField(blank=True, default='', help_text='Region or state', max_length=100, null=True)),
                ('country', models.CharField(default='Kenya', help_text='Country', max_length=100)),
                ('coordinates', models.CharField(blank=True, default='', help_text='GPS coordinates (latitude, longitude)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the destination is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='trucks_dest_name_34820e_idx'), models.Index(fields=['region'], name='trucks_dest_region_25f300_idx')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Driver's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Driver's last name", max_length=50)),
                ('license_number', models.CharField(help_text="Driver's license number", max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text="Driver's phone number", max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', help_text="Driver's email address", max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the driver is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks', null=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['license_number'], name='trucks_driv_license_cecef9_idx'), models.Index(fields=['first_name', 'last_name'], name='trucks_driv_first_n_31e504_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Transporter name', max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, default='', help_text='Primary contact person', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', help_text='Contact email address', max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='', help_text='Transporter address', null=True)),
                ('postal_address', models.CharField(blank=True, default='', help_text='Postal address (e.g., P.O. Box)', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the transporter is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks', null=True)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='trucks_tran_name_361d0d_idx'), models.Index(fields=['is_active'], name='trucks_tran_is_acti_618048_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier', max_length=50, unique=True)),
                ('invoice_date', models.DateField(help_text='Date when invoice was generated')),
                ('period_start', models.DateField(help_text='Start date of billing period')),
                ('period_end', models.DateField(help_text='End date of billing period')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Current invoice status', max_length=20)),
                ('total_transport_amount', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total transport charges', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_fuel_amount', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total fuel charges', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_credits', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits/deductions', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance', trucks.models.MoneyField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks for the invoice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(help_text='Transporter this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='trucks.transporter')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.CharField(help_text='Unique trip identifier', max_length=50, unique=True)),
                ('planned_departure', models.DateTimeField(blank=True, help_text='Planned departure date and time', null=True)),
                ('actual_departure', models.DateTimeField(blank=True, help_text='Actual departure date and time', null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, help_text='Planned arrival date and time', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, help_text='Actual arrival date and time', null=True)),
                ('cargo_description', models.CharField(blank=True, default='', help_text='Specific cargo description', max_length=200, null=True)),
                ('weight_tons', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight in tons', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivered_weight', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Actual weight delivered', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_per_ton', trucks.models.MoneyField(blank=True, decimal_places=2, help_text='Rate per ton', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transport_amount', trucks.models.MoneyField(blank=True, decimal_places=2, help_text='Total transport amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuel_amount', trucks.models.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total fuel cost for this trip', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='planned', help_text='Current trip status', max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('partial', 'Partial Delivery'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('returned', 'Returned')], default='pending', help_text='Delivery status', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Trip distance in kilometers', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about the trip', null=True)),
                ('source_document', models.CharField(blank=True, default='', help_text='Source document reference', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_type', models.ForeignKey(blank=True, help_text='Type of cargo being transported', null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.cargotype')),
                ('destination', models.ForeignKey(help_text='Trip destination location', on_delete=django.db.models.deletion.CASCADE, related_name='destination_trips', to='trucks.destination')),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trucks.driver')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice this trip belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trucks.invoice')),
                ('origin', models.ForeignKey(help_text='Trip origin location', on_delete=django.db.models.deletion.CASCADE, related_name='origin_trips', to='trucks.destination')),
                ('transporter', models.ForeignKey(help_text='Transporter/client', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trucks.transporter')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-planned_departure', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(choices=[('lost_bags', 'Lost Bags'), ('damaged_goods', 'Damaged Goods'), ('short_delivery', 'Short Delivery'), ('fuel_deduction', 'Fuel Deduction'), ('other', 'Other')], help_text='Type of credit/deduction', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity (bags, tons, etc.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount', trucks.models.MoneyField(decimal_places=2, help_text='Credit amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Description of the item/incident', max_length=200)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this credit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='trucks.invoice')),
                ('trip', models.ForeignKey(blank=True, help_text='Trip associated with this credit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='trucks.trip')),
            ],
            options={
                'verbose_name': 'Invoice Credit',
                'verbose_name_plural': 'Invoice Credits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of fuel purchase/consumption')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('other', 'Other')], default='diesel', help_text='Type of fuel', max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, help_text='Quantity of fuel in litres', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_per_litre', models.DecimalField(decimal_places=2, help_text='Cost per litre of fuel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_cost', trucks.models.MoneyField(blank=True, decimal_places=2, help_text='Total fuel cost', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuel_station', models.CharField(blank=True, default='', help_text='Fuel station name', max_length=100, null=True)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, help_text='Odometer reading at time of fueling', null=True)),
                ('receipt_number', models.CharField(blank=True, default='', help_text='Fuel receipt number', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about fuel record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(help_text='Trip this fuel record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='trucks.trip')),
            ],
            options={
                'verbose_name': 'Fuel Record',
                'verbose_name_plural': 'Fuel Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(help_text='Unique truck identifier/registration number', max_length=20, unique=True)),
                ('make', models.CharField(blank=True, default='', help_text='Truck make (e.g., Mercedes, Volvo)', max_length=50, null=True)),
                ('model', models.CharField(blank=True, default='', help_text='Truck model', max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True)),
                ('truck_type', models.CharField(choices=[('flatbed', 'Flatbed'), ('tanker', 'Tanker'), ('container', 'Container'), ('refrigerated', 'Refrigerated'), ('dump', 'Dump Truck'), ('other', 'Other')], default='flatbed', help_text='Type of truck', max_length=20)),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum capacity in tons', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fuel_tank_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel tank capacity in litres', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the truck is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional remarks', null=True)),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['truck_number'],
                'indexes': [models.Index(fields=['truck_number'], name='trucks_truc_truck_n_748e68_idx'), models.Index(fields=['is_active'], name='trucks_truc_is_acti_1a2169_idx')],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(help_text='Truck assigned to this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trucks.truck'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_level', models.CharField(choices=[('trip', 'Trip Level'), ('truck', 'Truck Level'), ('business', 'Business Level')], help_text='Level at which this expense is tracked', max_length=20)),
                ('description', models.CharField(help_text='Description of the expense', max_length=200)),
                ('amount', trucks.models.MoneyField(decimal_places=2, help_text='Expense amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date of expense')),
                ('receipt_number', models.CharField(blank=True, default='', help_text='Receipt or reference number', max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, default='', help_text='Vendor or service provider', max_length=100, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring expense (insurance, permits, etc.)')),
                ('remarks', models.TextField(blank=True, default='', help_text='Additional notes about the expense', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Expense category', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.expensecategory')),
                ('trip', models.ForeignKey(blank=True, help_text='Trip this expense belongs to (for trip-level expenses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.trip')),
                ('truck', models.ForeignKey(blank=True, help_text='Truck this expense belongs to (for truck-level expenses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('amount', trucks.models.MoneyField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('other', 'Other')], default='bank_transfer', help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Payment reference number', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, default='', help_text='Payment remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trucks.invoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['payment_date'], name='trucks_paym_payment_1fbe13_idx'), models.Index(fields=['invoice'], name='trucks_paym_invoice_848110_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='trucks_invo_invoice_3ca34e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='trucks_invo_status_8bb332_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['transporter', 'invoice_date'], name='trucks_invo_transpo_e0b343_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period_start', 'period_end'], name='trucks_invo_period__7ec589_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='valid_invoice_period'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='positive_total_amount'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('transporter', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['date'], name='trucks_fuel_date_225203_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelrecord',
            index=models.Index(fields=['trip'], name='trucks_fuel_trip_id_ff4caf_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trucks_trip_status_03bac2_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['planned_departure'], name='trucks_trip_planned_c4e7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['actual_departure'], name='trucks_trip_actual__a6a5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['truck'], name='trucks_trip_truck_i_e5025f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver'], name='trucks_trip_driver__fe00fd_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['transporter'], name='trucks_trip_transpo_56c505_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['invoice'], name='trucks_trip_invoice_379932_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='trucks_expe_date_5cebec_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_level'], name='trucks_expe_expense_ea4cac_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['trip'], name='trucks_expe_trip_id_a67031_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['truck'], name='trucks_expe_truck_i_cabbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='trucks_expe_categor_0c1eb3_idx'),
        ),
    ]
