# Generated by Django 5.2.4 on 2025-09-08 20:15

import django.core.validators
import django.db.models.deletion
import trucks.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='fuel_amount',
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_cost_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per litre of fuel for this trip', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_litres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total litres of fuel consumed for this trip', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_total_cost',
            field=trucks.models.MoneyField(blank=True, decimal_places=2, help_text='Total fuel cost for this trip', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_driver',
            field=models.ForeignKey(blank=True, help_text='Current driver assigned to this truck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trucks', to='trucks.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this trip — auto-filled from truck if not specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trucks.driver'),
        ),
    ]
