# Generated by Django 5.2.4 on 2025-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="The user's gross monthly salary.", max_digits=10),
        ),
    ]
