# Generated by Django 5.2.4 on 2025-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_basic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='waiter_reward_points',
            field=models.PositiveIntegerField(default=0, help_text="The waiter's current reward point balance."),
        ),
    ]
