# Generated by Django 5.2.4 on 2025-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_waiter_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_leaderboard_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Current bonus points from leaderboard position (changes dynamically)'),
        ),
    ]
