# Generated by Django 6.0.2 on 2026-04-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_leaderboard_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('room_manager', 'Room Manager'), ('waiter', 'Waiter'), ('kitchen_staff', 'Kitchen Staff'), ('bar_staff', 'Bar Staff'), ('butcher', 'Butcher'), ('cashier', 'Cashier')], default='waiter', max_length=20),
        ),
    ]
