# Generated by Django 6.0.2 on 2026-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('room_manager', 'Room Manager'), ('waiter', 'Waiter'), ('bar_staff', 'Bar Staff'), ('butcher', 'Butcher'), ('cashier', 'Cashier')], default='waiter', max_length=20),
        ),
    ]
