# Generated by Django 5.0.14 on 2025-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]



