# Generated by Django 5.0.14 on 2025-07-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_table_shape_alter_table_position_x_and_more'),
        ('schedule', '0003_swaprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftStockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar')], max_length=10)),
                ('opening_physical', models.DecimalField(decimal_places=3, max_digits=10)),
                ('closing_physical', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('opening_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('closing_system', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.menuitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='schedule.shift')),
            ],
            options={
                'unique_together': {('shift', 'item', 'section')},
            },
        ),
    ]



