# Generated by Django 5.0.14 on 2025-07-21 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_shiftstocktake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ['shift__start_datetime', 'user__first_name']},
        ),
        migrations.RemoveIndex(
            model_name='shift',
            name='schedule_sh_schedul_571579_idx',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(help_text="e.g. 'Night', 'Morning', 'Bar'", max_length=200),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['schedule', 'start_datetime'], name='schedule_sh_schedul_77c7ff_idx'),
        ),
    ]
