# Generated by Django 5.2.4 on 2025-08-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_shift_options_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['order', 'start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='shiftstocktake',
            options={'verbose_name': 'Shift Stock Take', 'verbose_name_plural': 'Shift Stock Takes'},
        ),
        migrations.AddField(
            model_name='shift',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='shift',
            field=models.ForeignKey(help_text='The shift the requester wants to give away', on_delete=django.db.models.deletion.CASCADE, to='schedule.shift'),
        ),
    ]



