# Generated by Django 5.2.4 on 2025-08-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_shift_options_alter_shiftstocktake_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='shiftstocktake',
            options={},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='order',
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.shift'),
        ),
    ]



