# Generated by Django 6.0.2 on 2026-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_shift_options_alter_shiftstocktake_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftstocktake',
            name='section',
            field=models.CharField(choices=[('Bar', 'Bar')], max_length=10),
        ),
    ]
