# Generated by Django 5.1.4 on 2025-06-17 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('module', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Butchery', 'Butchery')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Walking In', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, help_text="Customer's outstanding debt.", max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('supplies_to', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Butchery', 'Butchery')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'M-Pesa')], max_length=20)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.customer')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Final price to customer (for a menu dish or a raw item).', max_digits=10)),
                ('supplier_cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost price from the external supplier (per item or Kg).', max_digits=10)),
                ('internal_transfer_price', models.DecimalField(decimal_places=2, default=0, help_text="Value-added 'price' the Butchery charges the Kitchen.", max_digits=10)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Physical stock on hand. Only tracked for raw materials.', max_digits=10)),
                ('is_sold_by_weight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Is the item available for sale or use?')),
                ('ingredient_quantity_used', models.DecimalField(decimal_places=2, default=0, help_text='How much of the source ingredient is used (e.g., 0.5 Kg).', max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.category')),
                ('source_ingredient', models.ForeignKey(blank=True, help_text='Links a finished dish to the raw ingredient it consumes.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.delivery')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pos.customer')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'M-Pesa'), ('Credit', 'Credit')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('requested_from', models.CharField(choices=[('Butchery', 'Butchery'), ('Kitchen', 'Kitchen'), ('Grill', 'Grill'), ('Bar', 'Bar')], max_length=50)),
                ('requested_by_section', models.CharField(choices=[('Butchery', 'Butchery'), ('Kitchen', 'Kitchen'), ('Grill', 'Grill'), ('Bar', 'Bar')], max_length=50)),
                ('cost_at_transfer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfillment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_fulfilled', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
                ('requested_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.menuitem')),
            ],
            options={
                'ordering': ['-snapshot_date', 'menu_item__name'],
                'unique_together': {('menu_item', 'snapshot_date')},
            },
        ),
    ]
