# Generated by Django 5.1.4 on 2025-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_delivery_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The cost per unit/Kg at the time of delivery.', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requested_for_section',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar'), ('Butchery', 'Butchery')], default='Bar', help_text='The department this purchase order is for.', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The cost per unit/Kg at the time of order.', max_digits=10),
        ),
    ]



