# Generated by Django 5.1.4 on 2025-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_deliveryitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text="Set to 'Inactive' to hide from new purchase orders.", max_length=10),
        ),
    ]
