# Generated by Django 5.1.4 on 2025-06-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_supplier_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(help_text="e.g., 'Table 1', 'Bar Seat 3', 'Patio 5'", max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Needs Bill', 'Needs Bill')], default='Available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
