# Generated by Django 5.1.4 on 2025-06-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='The table this order is for. Leave blank for takeaway.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.table'),
        ),
    ]



