# Generated by Django 5.1.4 on 2025-06-22 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_customerpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The maximum credit amount that can be extended to this customer.', max_digits=10),
        ),
    ]



