# Generated by Django 5.1.4 on 2025-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_customer_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_kes', models.DecimalField(decimal_places=2, default=100.0, help_text='Amount in KES a customer must spend to earn 1 point. E.g., 100.', max_digits=10)),
                ('kes_per_point', models.DecimalField(decimal_places=2, default=1.0, help_text='Value of 1 loyalty point in KES during redemption. E.g., 1.00.', max_digits=10)),
                ('minimum_redeemable_points', models.PositiveIntegerField(default=50, help_text='The minimum number of points a customer must have to be able to redeem.')),
                ('is_active', models.BooleanField(default=True, help_text='Turn the entire loyalty system on or off.')),
            ],
            options={
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
    ]



