# Generated by Django 5.1.4 on 2025-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_loyaltysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text="The customer's current loyalty point balance."),
        ),
    ]



