# Generated by Django 5.1.4 on 2025-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_customer_loyalty_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="The unique code customers will enter (e.g., 'JULI-20' or 'APOLOGY-XYZ123').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text="Internal note about this coupon's purpose.")),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage Off'), ('Fixed', 'Fixed Amount Off (KES)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='The percentage (e.g., 10 for 10%) or the fixed amount in KES.', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(help_text='The coupon is valid up to the end of this day.')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Max number of times this coupon can be used in total.')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]



