# Generated by Django 5.1.4 on 2025-06-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_expensecategory_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.order'),
        ),
    ]



