# Generated by Django 5.1.4 on 2025-06-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_sale_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredient_quantity_used',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='internal_transfer_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='source_ingredient',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the menu item, displayed on the POS.', null=True, upload_to='menu_item_images/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_recipe',
            field=models.BooleanField(default=False, help_text='Check this if this item is a finished dish made from other ingredients.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='When stock quantity reaches this level, an alert will be triggered.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price to customer (for menu dishes or direct sale items).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Physical stock on hand. Only tracked for raw materials and direct sale items.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='supplier_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price from the supplier (for raw materials).', max_digits=10),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of the ingredient required for one serving of the dish.', max_digits=10)),
                ('dish', models.ForeignKey(limit_choices_to={'is_recipe': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='pos.menuitem', verbose_name='Finished Dish')),
                ('ingredient', models.ForeignKey(limit_choices_to={'is_recipe': False}, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_for', to='pos.menuitem')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'unique_together': {('dish', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='used_in_dishes', through='pos.RecipeIngredient', to='pos.menuitem'),
        ),
    ]



