# Generated by Django 5.1.4 on 2025-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_remove_menuitem_ingredient_quantity_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('pc', 'Pieces')], default='pc', help_text='The unit this item is measured in for inventory purposes.', max_length=10),
        ),
    ]
