# Generated by Django 5.0.14 on 2025-06-30 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_menuitem_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pos.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
