# Generated by Django 5.0.14 on 2025-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_alter_delivery_delivery_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.IntegerField(default=0, help_text='X-coordinate for the table layout editor.'),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Y-coordinate for the table layout editor.'),
        ),
    ]
