# Generated by Django 5.0.14 on 2025-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_table_position_x_table_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('round', 'Round')], default='square', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_x',
            field=models.IntegerField(default=0, help_text='X-coordinate for drag layout.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Y-coordinate for drag layout.'),
        ),
    ]



