# Generated by Django 5.2.4 on 2025-07-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_table_shape_alter_table_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='The default supplier to reorder this item from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=10, help_text='The default quantity to order when stock is low.', max_digits=10),
        ),
    ]
