# Generated by Django 5.2.4 on 2025-07-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_menuitem_preferred_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Partially Received', 'Partially Received'), ('Fully Received', 'Fully Received')], default='Pending', max_length=20),
        ),
    ]



