# Generated by Django 5.2.4 on 2025-07-30 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='pos.menuitem'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Resolved', 'Resolved')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='stock_level_at_alert',
            field=models.DecimalField(decimal_places=2, help_text='Stock level when the alert was created', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['status', '-created_at'], name='pos_stockal_status_ee9d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['menu_item', 'status'], name='pos_stockal_menu_it_b9073f_idx'),
        ),
    ]
