# Generated by Django 5.2.4 on 2025-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_stockalert_notes_alter_stockalert_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_sold_by_weight',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sell_by_weight',
            field=models.BooleanField(default=False, help_text="Can be sold by total amount (e.g., 'KES 700 of beef')"),
        ),
    ]



