# Generated by Django 5.2.4 on 2025-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_remove_menuitem_is_sold_by_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]



