# Generated by Django 5.2.4 on 2025-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_stocktransfer_transferred_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterRewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_kes', models.DecimalField(decimal_places=2, default=100.0, help_text="Amount in KES a waiter's sale must be to earn 1 point. E.g., 100.", max_digits=10)),
                ('kes_per_point', models.DecimalField(decimal_places=2, default=1.0, help_text='Monetary value of 1 waiter point (for future redemption or bonus calculation). E.g., 1.00.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Turn the entire waiter reward system on or off.')),
            ],
            options={
                'verbose_name_plural': 'Waiter Reward Settings',
            },
        ),
    ]
