# Generated by Django 5.2.4 on 2025-10-30 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_alter_menuitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_auth_code',
            field=models.CharField(blank=True, help_text='6-digit code for manager authorization of cancellation', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the waiter requested cancellation', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_by',
            field=models.ForeignKey(blank=True, help_text='Waiter who requested cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
