# Generated by Django 5.2.4 on 2025-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_order_cancellation_auth_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterrewardsettings',
            name='bronze_bonus_points',
            field=models.PositiveIntegerField(default=150, help_text='Bonus points awarded to 3rd place waiter'),
        ),
        migrations.AddField(
            model_name='waiterrewardsettings',
            name='gold_bonus_points',
            field=models.PositiveIntegerField(default=500, help_text='Bonus points awarded to 1st place waiter'),
        ),
        migrations.AddField(
            model_name='waiterrewardsettings',
            name='leaderboard_reset_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often the leaderboard resets (for display purposes - bonuses are always live)', max_length=20),
        ),
        migrations.AddField(
            model_name='waiterrewardsettings',
            name='silver_bonus_points',
            field=models.PositiveIntegerField(default=300, help_text='Bonus points awarded to 2nd place waiter'),
        ),
    ]



