# Generated by Django 6.0.2 on 2026-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_waiterrewardsettings_bronze_bonus_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Always saved in uppercase.', max_length=255, unique=True),
        ),
    ]
