# Generated by Django 6.0.2 on 2026-04-14 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pos', '0033_alter_menuitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Price Change', 'Price Change'), ('Stock Adjustment', 'Stock Adjustment'), ('Order Cancellation', 'Order Cancellation'), ('Delivery Received', 'Delivery Received'), ('Expense Recorded', 'Expense Recorded'), ('Payroll Processed', 'Payroll Processed'), ('Stock Transfer', 'Stock Transfer'), ('General', 'General')], max_length=50)),
                ('description', models.TextField()),
                ('object_id', models.CharField(max_length=255, null=True)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', '-timestamp'], name='pos_auditlo_action__ffad2d_idx'), models.Index(fields=['content_type', 'object_id'], name='pos_auditlo_content_1d0447_idx')],
            },
        ),
    ]
