# Generated by Django 6.0.2 on 2026-04-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent category (leave blank for a top-level category).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pos.category'),
        ),
    ]
