# Generated by Django 6.0.2 on 2026-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_add_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='module',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Butchery', 'Butchery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='requested_for_section',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Butchery', 'Butchery')], default='Bar', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='requested_by_section',
            field=models.CharField(choices=[('Butchery', 'Butchery'), ('Grill', 'Grill'), ('Bar', 'Bar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='requested_from',
            field=models.CharField(choices=[('Butchery', 'Butchery'), ('Grill', 'Grill'), ('Bar', 'Bar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplies_to',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Butchery', 'Butchery')], max_length=50),
        ),
    ]
