"""
Django settings for riziki project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os.path
from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#4$82_!7r+_jz^4==n@%y(b!m_%nbj=+#2v1ql-(29md8z4*qb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['julisfarm.pythonanywhere.com', 'localhost', '127.0.0.1', 'www.julisfarm.pythonanywhere.com']

MENU_PAGE_SIZE = 10      # adjust as desired
# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'dal_legacy_static',
    'unfold',
    'unfold.contrib.import_export',
    'import_export',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.flatpages',
    'django.contrib.sites',
    'accounts.apps.AccountsConfig',
    'core.apps.CoreConfig',
    'pos.apps.PosConfig',
    'tg_bot.apps.TgBotConfig',
    'trucks.apps.TrucksConfig',
    'julifarm.apps.JulifarmConfig',
    'payroll.apps.PayrollConfig',
    'imagekit',
    'crispy_forms',
    'crispy_tailwind',
    'schedule.apps.ScheduleConfig',
    'rooms.apps.RoomsConfig',
    'tinymce',
    'django_select2',
    'django_filters',
    'smart_selects',
    'django_htmx',
    'django_htmx_refresh',
    'django.contrib.humanize',



]
CRISPY_ALLOWED_TEMPLATE_PACKS = ("tailwind",)
SITE_ID = 1
CRISPY_TEMPLATE_PACK = "tailwind"
USE_DJANGO_JQUERY = True
JQUERY_URL = False

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_htmx.middleware.HtmxMiddleware',
    'core.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = "hotela.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],

        },
    },
]

WSGI_APPLICATION = "hotela.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = 'accounts.User'
ADMIN_ENABLE_THEMING = False

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# Enable timezone support
USE_TZ = True

# Set your local timezone - for Nairobi, Kenya
TIME_ZONE = 'Africa/Nairobi'  # UTC+3

# Alternative timezone settings you might need:
# TIME_ZONE = 'UTC'  # If you want everything in UTC
# TIME_ZONE = 'Africa/Dar_es_Salaam'  # Also UTC+3 (Tanzania)
# TIME_ZONE = 'Indian/Antananarivo'  # UTC+3 (Madagascar)

# Language and formatting
LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True

# Optional: If you want to display times in a specific format
DATETIME_FORMAT = 'Y-m-d H:i:s'
TIME_FORMAT = 'H:i:s'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

UNFOLD = {
    "SITE_TITLE": "JuliFarm Admin",
    "SITE_HEADER": "JuliFarm Admin",
    "SITE_URL": reverse_lazy("pos:pos"),  # uses named URL
    "MENU": [
        {
            "label": "Go to Site",
            "icon": "heroicons-outline:external-link",
            "url": reverse_lazy("pos:pos"),
            "target": "_blank",
        },
    ],
}
TELEGRAM_BOT_TOKEN = "8089993818:AAGC6-V5zwCAzTDQ3NzyNJsL_DII9RWrRnU"