# Generated by Django 5.1.4 on 2025-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('julifarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='category_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=10),
        ),
    ]
