from django.urls import path
from . import views
from .views import PurchaseOrderCreateView, PurchaseOrderDetailView

app_name = 'pos'
urlpatterns = [
    path('pos/', views.pos, name='pos'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/add/', views.supplier_add, name='supplier_add'),
    path('suppliers/edit/<int:pk>/', views.supplier_edit, name='supplier_edit'),
    path('management/categories/', views.category_list_view, name='category_list'),
    path('management/categories/add/', views.category_add, name='category_add'),
    path('management/categories/edit/<int:pk>/', views.category_edit, name='category_edit'),
    path('management/categories/delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('management/menu/', views.menu_item_list_view, name='menu_item_list'),
    path('management/menu/add/', views.menu_item_add, name='menu_item_add'),
    path('management/menu/edit/<int:pk>/', views.menu_item_edit, name='menu_item_edit'),
    path('management/menu/delete/<int:pk>/', views.menu_item_delete, name='menu_item_delete'),
    path('alerts/dismiss/<int:pk>/', views.dismiss_stock_alert, name='dismiss_stock_alert'),
    path('management/audit-logs/', views.audit_log, name='audit_log'),
    path('procurement/purchase-orders/', views.purchase_order_list, name='purchase_order_list'),
    path('procurement/purchase-orders/new/', views.purchase_order_create, name='purchase_order_create'),
    path('procurement/purchase-orders/<int:pk>/', views.purchase_order_detail, name='purchase_order_detail'),
    path('procurement/purchase-edit/<int:pk>/', views.purchase_order_edit, name='purchase_order_edit'),

    path('procurement/receive-delivery/from-po/<int:po_id>/', views.receive_delivery_from_po, name='receive_delivery_from_po'),
    path('reports/variance/all/', views.po_variance_report_all, name='po_variance_report_all'),
    path('reports/variance/supplier/<int:pk>/', views.po_variance_report_supplier, name='po_variance_report_supplier'),
    path('waiter/dashboard/', views.waiter_dashboard, name='waiter_dashboard'),
    path('order/new/', views.create_order, name='create_order'),
    path('order/detail/<int:order_id>/', views.waiter_order_detail, name='waiter_orderdetail'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
    # HTMX URLs remain the same
    path('htmx/add-item/', views.htmx_add_order_item, name='htmx_add_order_item'),
    path('htmx/remove-item/', views.htmx_remove_order_item, name='htmx_remove_order_item'),
    path('htmx/delete-item/', views.htmx_delete_order_item, name='htmx_delete_order_item'),
    path('htmx/clear-cart/', views.htmx_clear_cart, name='htmx_clear_cart'),
    path('order/menu-content/', views.htmx_menu_content, name='htmx_menu_content'),
    path('htmx/order/<int:order_id>/mark-ready/<str:module>/', views.htmx_mark_items_ready,
         name='htmx_mark_items_ready'),
    path('display/kitchen/', views.kitchen_display_view, name='kitchen_display'),
    path('display/bar/', views.bar_display_view, name='bar_display'),
    # HIGHLIGHT: New URL to process the final submission of the tabbed order form
    path('order/finalize/', views.finalize_orders, name='finalize_orders'),
    path('htmx/menu-panel/', views.htmx_menu_panel, name='htmx_menu_panel'),
    # --- PRINTING & BILLING ---
    # HIGHLIGHT: New URL to print a single production docket (Kitchen/Bar)
    path('order/<int:order_id>/print/', views.print_order_receipt, name='print_order_receipt'),
    path('print/kitchen-docket/<int:order_id>/', views.print_kitchen_docket, name='print_kitchen_docket'),
    path('print/bar-docket/<int:order_id>/', views.print_bar_docket, name='print_bar_docket'),
    path('orders/<int:order_id>/multi-payment/',
         views.htmx_multi_payment_modal,
         name='htmx_multi_payment_modal'),

    path('pos/orders/<int:order_id>/add-payment/',
         views.add_single_payment,
         name='add_single_payment'),

    path('pos/orders/<int:order_id>/remove-payment/',
         views.remove_pending_payment,
         name='remove_pending_payment'),
    path('toggle-menu-item-active/<int:item_id>/', views.toggle_menu_item_active, name='toggle_menu_item_active'),
    path('edit-menu-item/<int:item_id>/', views.edit_menu_item_ajax, name='edit_menu_item_ajax'),
    path('pos/orders/<int:order_id>/complete-multi-payment/',
         views.complete_multi_payment_order,
         name='complete_multi_payment_order'),
    path('htmx/item/<int:item_id>/add-modal/', views.htmx_item_add_modal, name='htmx_item_add_modal'),
    path('pos/orders/<int:order_id>/process-multi-payment/',
         views.process_multi_payment,
         name='process_multi_payment'),
    path('clear-duplicate-cache/', views.clear_duplicate_cache, name='clear_duplicate_cache'),
    path('pos/orders/<int:order_id>/pending-payments/',
         views.get_pending_payments,
         name='get_pending_payments'),
    path('duplicate-menu-items/', views.duplicate_menu_items_view, name='duplicate_menu_items'),
    path('bulk-manage-duplicates/', views.bulk_manage_duplicates, name='bulk_manage_duplicates'),
    path('menu-item/<int:item_id>/edit/', views.edit_menu_item_ajax, name='edit_menu_item_ajax'),
    path('dismiss-duplicate-group/<int:group_index>/', views.dismiss_duplicate_group, name='dismiss_duplicate_group'),
    path('dismiss-all-dashboard-duplicates/', views.dismiss_all_dashboard_duplicates, name='dismiss_all_dashboard_duplicates'),
    # Print optimization endpoints

    # HIGHLIGHT: New URL to generate the final consolidated customer bill for a table
    path('bill/table/<int:table_id>/', views.generate_table_bill, name='generate_table_bill'),
    path('htmx/menu-grid/', views.htmx_menu_grid, name='htmx_menu_grid'),
    path('station/<str:section>/', views.unified_station_view, name='unified_station_view'),
    path('dismiss-alert/<int:alert_id>/', views.dismiss_alert, name='dismiss_alert'),
    path('dismiss-all-alerts/', views.dismiss_all_alerts, name='dismiss_all_alerts'),
    path('approve-purchase-order/<int:po_id>/', views.approve_purchase_order, name='approve_purchase_order'),
    path('dismiss-purchase-order/<int:po_id>/', views.dismiss_purchase_order, name='dismiss_purchase_order'),
    path('approve-all-purchase-orders/', views.approve_all_purchase_orders, name='approve_all_purchase_orders'),
    path('dismiss-all-purchase-orders/', views.dismiss_all_purchase_orders, name='dismiss_all_purchase_orders'),
    # New URL for the payment modal
    path('htmx/payment-modal/<int:order_id>/', views.htmx_payment_modal, name='htmx_payment_modal'),
    path('process-payment/order/<int:order_id>/', views.process_order_payment, name='process_order_payment'),
    # New URL for marking ready
    path('htmx/order/<int:order_id>/ready-and-print/', views.htmx_mark_as_ready_and_print, name='htmx_ready_and_print'),
    path('htmx/awaiting-payment/<str:section>/', views.htmx_awaiting_payment_list, name='htmx_awaiting_payment_list'),
    path('htmx/order-item/<int:item_id>/ready/', views.htmx_mark_one_item_ready, name='htmx_mark_one_item_ready'),
    path('reports/sales/', views.sales_report_view, name='sales_report'),
    path('reports/sales/print/', views.print_sales_report_view, name='print_sales_report'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.customer_add, name='customer_add'),
    path('customers/edit/<int:pk>/', views.customer_edit, name='customer_edit'),
    path('customers/delete/<int:pk>/', views.customer_delete, name='customer_delete'),
    path('management/tables/', views.table_list, name='table_list'),
    path('management/tables/add/', views.table_add, name='table_add'),
    path('management/tables/edit/<int:pk>/', views.table_edit, name='table_edit'),
    path('management/tables/delete/<int:pk>/', views.table_delete, name='table_delete'),
    path('payments/customer/', views.customer_payment_list, name='customer_payment_list'),
    path('payments/customer/add/', views.add_customer_payment, name='add_customer_payment'),
    path('reports/credit-sales/', views.credit_sales_report_view, name='credit_sales_report'),
    path('reports/credit-sales/print/', views.print_credit_sales_report_view, name='print_credit_sales_report'),
    path('htmx/customer-balance/', views.htmx_get_customer_balance, name='htmx_get_customer_balance'),
    path('htmx/apply-loyalty/<int:order_id>/', views.htmx_apply_loyalty_discount, name='htmx_apply_loyalty_discount'),
    path('htmx/apply-coupon/<int:order_id>/', views.htmx_apply_coupon, name='htmx_apply_coupon'),
    path('expenses/', views.expense_list, name='expense_list'),
    path('management/tables/layout/', views.table_layout_editor_view, name='table_layout_editor'),
    path('management/tables/layout/save/', views.save_table_layout_view, name='save_table_layout'),
    path('order/new/for-table/<int:table_id>/', views.create_order_for_table, name='create_order_for_table'),
    path('order/manage/<int:order_id>/', views.waiter_order_detail_view, name='waiter_order_detail'),
    path('table/<int:table_id>/', views.table_detail_view, name='table_detail'),
    path('print/consolidated-bill/', views.print_consolidated_bill, name='print_consolidated_bill'),

    # HTMX URLs for order management
    path('htmx/order-item/remove/<int:item_id>/', views.htmx_remove_item_from_order,
         name='htmx_remove_item_from_order'),
    path('htmx/order/cancel/<int:order_id>/', views.htmx_cancel_order, name='htmx_cancel_order'),

    # The page with the form to add a new expense
    path('expenses/add/', views.expense_add, name='expense_add'),
    path('tables/reset/', views.reset_table_layout_view, name='reset_table_layout'),
    # The page to edit an existing expense record
    path('expenses/edit/<int:pk>/', views.expense_edit, name='expense_edit'),
    path('order/add-items/<int:order_id>/', views.add_items_to_order_view, name='add_items_to_order'),
    # The page to confirm the deletion of an expense record

    path('butchery/quick-sell/', views.butchery_section_quick_sell_view, name='butchery_section_quick_sell'),
    # The dedicated URL for the printer-friendly version of the report
    path('expenses/print/', views.print_expense_report_view, name='print_expense_report'),
    path('management/expense-categories/', views.expense_category_list, name='expense_category_list'),
    path('management/expense-categories/add/', views.expense_category_add, name='expense_category_add'),
    path('management/expense-categories/edit/<int:pk>/', views.expense_category_edit, name='expense_category_edit'),
    path('management/expense-categories/delete/<int:pk>/', views.expense_category_delete, name='expense_category_delete'),
    path('expenses/delete/<int:pk>/', views.expense_delete, name='expense_delete'),
    path('htmx/customer-search/', views.htmx_customer_search, name='htmx_customer_search'),
    path('print/receipt/<int:sale_id>/', views.print_customer_receipt, name='print_customer_receipt'),
    path('htmx/live-tickets/<str:section>/', views.htmx_live_order_tickets, name='htmx_live_order_tickets'),
    path('htmx/awaiting-payment/<str:section>/', views.htmx_awaiting_payment_list, name='htmx_awaiting_payment_list'),
    path('butchery/', views.butchery_section_view, name='butchery_section'),
    path('butchery/transfer/', views.butchery_transfer_view, name='butchery_transfer'),
    path('butchery-pos/', views.butchery_pos_view, name='butchery_pos'),
    path('butchery-pos/finalize/', views.finalize_butchery_order, name='finalize_butchery_order'),
    path('menu/', views.public_menu_landing, name='public_menu'),
    # Stock Transfer URLs
    path('stock/request/', views.stock_request_create_view, name='stock_request_create'),
    path('stock/requests/', views.stock_request_list_view, name='stock_request_list'),
    path('stock/request/<int:pk>/fulfill/', views.fulfill_stock_request_view, name='fulfill_stock_request'),
    path('purchases/new/', PurchaseOrderCreateView.as_view(), name='purchase_order_create'),
    path('purchases/<int:pk>/', views.purchase_order_detail, name='purchase_order_detail'),
    path('orders/<int:order_id>/request-cancellation/',
         views.request_order_cancellation,
         name='request_cancellation'),
    path('orders/<int:order_id>/authorize-cancellation/',
         views.authorize_order_cancellation,
         name='authorize_cancellation'),
    path('cashier/', views.cashier_dashboard, name='cashier_dashboard'),
    path('cashier/orders/refresh/', views.htmx_refresh_cashier_orders, name='htmx_refresh_cashier_orders'),
    path('cashier/stock-printout/', views.daily_stock_printout, name='daily_stock_printout'),
    path('cashier/debt-payment/modal/', views.htmx_customer_payment_modal, name='htmx_customer_payment_modal'),
    path('cashier/debt-payment/modal/<int:customer_id>/', views.htmx_customer_payment_modal, name='htmx_customer_payment_modal_specific'),
    path('cashier/debt-payment/process/', views.htmx_process_customer_payment, name='htmx_process_customer_payment'),
]






